### ISSUE TITLE
SharedPreferenceCheck is throwing a null pointer exception on run

### ISSUE THREAD

**Issue by StevenPG** [StevenPG/ProjectManagement#5]
Hector, I've commented out the SharedPreferenceCheck call for now, I was unable to remove the exception. Hopefully you can look into wrapping the call in an object so we can work on it further some time down the line. I think we should focus on the general activity for now.

**Comment by StevenPG** [comment]
Here is a short snippet of the exception:

 at com.kutztown.projectmanagement.data.SharePreferenceCheck.preference(SharePreferenceCheck.java:18)
                                                                                            at com.kutztown.projectmanagement.activity.SplashActivity$1.run(SplashActivity.java:70)

**Comment by StevenPG** [comment]
Hector has mentioned that this is currently working.
